// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opluoazxrbmisnvxiuuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbHVvYXp4cmJtaXNudnhpdXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NTU4ODUsImV4cCI6MjA3MzAzMTg4NX0._69x_uEw8k6umJ46h2ma217UKjd2JhBITUkVe5cq1J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});